name: Push or Pull
on: [push, pull_request]

env:
  MESSAGE_PUSH: "C'est un push !"
  MESSAGE_PULL: "C'est une pull request !"

jobs:
  say-push:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push' }}
    steps:
      - name: "Dit push"
        run: echo "$MESSAGE_PUSH"
    
  say-pull:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request' }}
    steps:
      - name: "Dit pull request"
        run: echo "$MESSAGE_PULL"