name: DL artifact

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: echo "HELLO" > artifact2.txt
      - name: upload2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: artifact2.txt
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact2
      - name: read-file
        run: cat artifact2.txt