name: hello-world
on: push
jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout du code
        uses: actions/checkout@v4
      - name: Say Hello World !
        run: echo "Hello World!"